### ISSUE TITLE
Error while using device="cpu" with scg.tasks.embed_data

### ISSUE THREAD

**Issue by mksingh2104** [bowang-lab/scGPT#109]
Hi there, 

I am trying to use device="cpu" with scg.tasks.embed_data and getting following error. Any help would be greatly appreciated. 

---------------------
Traceback (most recent call last):
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/scgpt/tasks/cell_emb.py", line 258, in embed_data
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "cls_decoder._decoder.0.weight", "cls_decoder._decoder.0.bias", "cls_decoder._decoder.2.weight", "cls_decoder._decoder.2.bias", "cls_decoder._decoder.3.weight", "cls_decoder._decoder.3.bias", "cls_decoder._decoder.5.weight", "cls_decoder._decoder.5.bias", "cls_decoder.out_layer.weight", "cls_decoder.out_layer.bias".
	Unexpected key(s) in state_dict: "flag_encoder.weight".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/scGPT/test2120/reference_mapping/reference_mapping_cpu.py", line 45, in <module>
    test_embed_adata = scg.tasks.embed_data(
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/scgpt/tasks/cell_emb.py", line 261, in embed_data
    pretrained_dict = torch.load(model_file)
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ec2-user/scGPT/scgptenv/lib64/python3.9/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by subercui** [comment]
Hi, thank you for the question! I have updated the code to support better running on CPU and native pytorch. Please pull the newest commit and have a try with the `embed_data` as shown this example from https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Reference_Mapping.ipynb 

![image](https://github.com/bowang-lab/scGPT/assets/11674033/ff1e7f7b-5543-492b-9b05-72a2ccf7770d)

Let me know how it works.

**Comment by docmab23** [comment]
<img width="660" alt="image" src="https://github.com/bowang-lab/scGPT/assets/31487695/bee8c5f6-1b84-49d0-92c6-bfaf8ce828b3">


Using a "cpu" still doesn't seem to work 


<img width="910" alt="image" src="https://github.com/bowang-lab/scGPT/assets/31487695/3a55078f-5535-4d4c-b937-d64a474f7a58">

**Comment by docmab23** [comment]
Actually, it worked, changed this line in  `./tasks/cell_emb.py`: 

 `load_pretrained(model, torch.load(model_file, map_location=torch.device('cpu')), verbose=False)`

**Comment by subercui** [comment]
Thanks, glad to know that! It seems by default the map location will still be cuda even on CPU-only machine. I will update that line.

By the way, running on cpu can be slow. It can take tens of minis for embedding several thousands of cells. Therefore, I would recommend having a look at these [online tools](https://github.com/bowang-lab/scGPT#online-apps) for running the analysis on the cloud. We are also working on a web app platform at scgpthub.org

**Comment by mksingh2104** [comment]
Hi there, 

Thank you for your response.

I am able to run scg.tasks.embed_data on CPU only machine. 
I needed to uninstall flash-attn,  and add map_location=torch.device('cpu') in code.

Yes, it runs very slow. 

Sincerely,

**Comment by subercui** [comment]
Thank you, I have fixed it. In the meantime, I will strongly recommend running on GPUs. You can actually run it on google collab now with their provided GPU. You may find these examples useful, https://github.com/bowang-lab/scGPT/tree/main/tutorials/zero-shot
